public class Calculator {
    integer a=50;
    integer b=10;
    public void add(){
        integer sum=a+b;
        System.debug('Addition of two number is '+sum);
    }
    
    public void sub(){
        integer sum=a-b;
        System.debug('Substraction of two number is '+sum);
    }
        public void multi(){
        integer sum=a*b;
        System.debug('Multiplication of two number is '+sum);
    }
        public void div(){
        integer sum=a/b;
        System.debug('division of two number is '+sum);
    }
}